image: Visual Studio 2022

configuration:
  - Release
  - Debug

platform:
  - x64

install:
  - git submodule update --init --recursive

build_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=%CONFIGURATION% -G "Visual Studio 17 2022" -A x64 -DBRIDGE_BUILD_TESTS=ON  ..
  - cmake --build . --config %CONFIGURATION%
  - ctest --output-on-failure -C %CONFIGURATION%
